import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';

type Props = { params: Promise<{ locale: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { locale } = await params;
    const isEn = locale === 'en';
    return {
        title: isEn
            ? 'AI Zi Wei Dou Shu - Modern Chinese Astrology System'
            : 'AI 紫微斗數 - 現代化的命理分析系統',
        description: isEn
            ? 'Combining traditional Zhongzhou school theory with modern AI technology for accurate destiny analysis.'
            : '結合傳統中州派理論與現代 AI 技術，提供精準的命理分析。支援農曆西曆轉換，自動計算命盤，並提供 AI 深度解析。',
        openGraph: {
            images: [{ url: 'https://aiziwei.online/og-image.png', width: 1200, height: 630 }],
        },
        twitter: { card: 'summary_large_image', images: ['https://aiziwei.online/og-image.png'] },
        alternates: {
            canonical: `https://aiziwei.online/${locale}/`,
            languages: { 'zh-TW': 'https://aiziwei.online/zh-TW/', 'en': 'https://aiziwei.online/en/' },
        },
    };
}

export default async function HomePage({ params }: Props) {
    const { locale } = await params;
    const isEn = locale === 'en';
    const analysisHref = `/${locale}/analysis`;

    const t = isEn ? {
        hero: {
            title: 'AI Zi Wei Dou Shu',
            subtitle: 'Combining traditional astrological wisdom with modern AI technology\nfor deeper, more accurate destiny analysis.',
            cta: '✨ Experience AI Destiny Analysis Now',
        },
        about: {
            badge: 'About Us',
            heading: 'What is AI Zi Wei Dou Shu?',
            sub: 'Bridging millennia of astrological wisdom with modern AI to make traditional culture part of everyday life',
            card1Title: 'Historical Origins of Zi Wei Dou Shu',
            card1p1: <><strong>Zi Wei Dou Shu</strong>, also known as "Purple Star Astrology", is one of the most important astrological systems in traditional Chinese divination. Its origins trace back to the <strong>Tang Dynasty</strong>, founded by <strong>Zhang Guo Lao</strong> and later developed by <strong>Chen Xi Yi</strong> and others.</>,
            card1p2: <>It centers on the <strong>Purple Star (Ziwei)</strong>, combining the <strong>Twelve Palaces</strong>, <strong>Fourteen Major Stars</strong>, <strong>Six Auspicious Stars</strong>, <strong>Six Inauspicious Stars</strong>, and the dynamic <strong>Four Transformations</strong> (Wealth, Power, Fame, Obstruction), forming a complete destiny analysis system.</>,
            card1p3: <>Through the <strong>Song, Yuan, Ming, and Qing</strong> dynasties, Zi Wei Dou Shu became one of the four major divination systems alongside <strong>Ba Zi</strong>, <strong>Face Reading</strong>, and <strong>Feng Shui</strong>.</>,
            card2Title: 'Why the Zhongzhou School?',
            card2p: <>The Zhongzhou School (Heluo School) is one of the oldest and most rigorous lineages, rooted in classical Central Plains tradition. It emphasises <strong>precise star energy rankings</strong>, the dynamic interplay of the <strong>Four Transformations</strong>, and the systematic logic of <strong>flying stars</strong> — giving our AI a clear logical basis for chart interpretation.</>,
            card3Title: 'How Is Our Content Generated?',
            card3p: <>All blog articles are <strong>automatically generated by AI</strong>, combining Zhongzhou School theory with current <strong>solar terms</strong>, <strong>lunar calendar events</strong>, and trending topics — written in plain, accessible language. Our goal: traditional astrology as a cultural tool for self-understanding, not mystical fortune-telling.</>,
        },
        faq: {
            heading: '🙋 Frequently Asked Questions',
            items: [
                {
                    q: 'What is the difference between Zi Wei Dou Shu and Ba Zi?',
                    a: 'Zi Wei Dou Shu centres on stars and twelve palaces, excelling at nuanced personality analysis across life domains (wealth, career, relationships, etc.). Ba Zi uses Five Elements theory to map major luck cycles. Both have unique strengths and complement each other.',
                },
                {
                    q: 'How does the Zhongzhou School differ from other lineages?',
                    a: 'Rooted in classical Central Plains tradition, the Zhongzhou School emphasises precise star energy rankings, Four Transformation dynamics, and rigorous flying-star logic. Compared to modern derivative schools, it more faithfully preserves the traditional framework — ideal for systematic study and AI-structured analysis.',
                },
                {
                    q: 'Who writes the articles on this website?',
                    a: 'All articles are automatically generated by our AI system, which combines Zhongzhou School theory with current solar terms, lunar dates, and trending topics to produce easy-to-read astrological reference content.',
                },
                {
                    q: 'How accurate is the AI analysis?',
                    a: 'Our system uses a leading AI language model combined with traditional Zhongzhou School theory. The AI systematically integrates chart combinations to provide objective reference. Destiny analysis is a cultural tradition — best used as a tool for self-understanding and finding your rhythm, not as absolute prediction.',
                },
                {
                    q: "What if I don't know my birth hour?",
                    a: 'An accurate Zi Wei Dou Shu chart requires the birth hour (each two-hour block is one time period). If uncertain, you can try the closest time period, cross-reference major life events to narrow it down, or consult an experienced astrologer.',
                },
                {
                    q: "What's the difference between blog articles and a personal reading?",
                    a: <span>Blog articles interpret current events, solar terms, and fortune trends from an astrological perspective — suitable for general reading and learning. For a personalised chart analysis based on your birth data, use the <Link href={analysisHref} className="text-purple-600 hover:underline">Start Analysis</Link> feature.</span>,
                },
            ],
        },
        cta: {
            heading: 'Ready to Explore Your Destiny?',
            sub: <>Combining traditional Zhongzhou wisdom with modern AI<br />for the most professional, accessible destiny analysis</>,
            button: '🚀 Start AI Destiny Analysis Now',
            disclaimer: '⚠️ This service is for entertainment and cultural learning purposes only, and should not be used as the basis for important life decisions.',
        },
        footer: {
            copyright: '© 2024 AI Zi Wei Dou Shu | Based on Traditional Zhongzhou School Theory',
            privacy: 'Privacy Policy',
            pricing: 'Pricing',
            analysis: 'Start Analysis',
        },
    } : {
        hero: {
            title: 'AI 紫微斗數',
            subtitle: '結合傳統命理智慧與現代 AI 技術\n為您提供更準確、更深入的命理分析',
            cta: '✨ 立即體驗 AI 命理分析',
        },
        about: {
            badge: '關於我們',
            heading: 'AI 紫微斗數是什麼？',
            sub: '結合千年命理智慧與現代 AI 技術，讓傳統文化走入日常生活',
            card1Title: '紫微斗數的歷史淵源',
            card1p1: <><strong>紫微斗數</strong>，又稱「紫微命盤」，是中國傳統命理學中極為重要的占星術系統。其起源可追溯至<strong>唐代</strong>，由<strong>張果老</strong>所創立，後經由<strong>陳希夷</strong>等人傳承發展。</>,
            card1p2: <>紫微斗數以<strong>紫微星</strong>為核心，結合<strong>十二宮位</strong>、<strong>十四主星</strong>、<strong>六吉星</strong>、<strong>六煞星</strong>，以及<strong>四化星</strong>（化祿、化權、化科、化忌）的動態變化，形成一套完整的命理分析體系。</>,
            card1p3: <>歷經<strong>宋、元、明、清</strong>各朝的發展，紫微斗數逐漸成為與<strong>八字</strong>、<strong>面相</strong>、<strong>風水</strong>並列的四大命理體系之一。</>,
            card2Title: '為什麼選擇中州派？',
            card2p: <>中州派（又稱河洛派）源自中原正統，是紫微斗數流傳最久、理論最嚴謹的主要流派之一。特別重視<strong>星曜能量等級</strong>的精確評估、<strong>四化星</strong>在宮位之間的動態互動，以及<strong>飛星邏輯</strong>的系統推演。這套嚴謹的分析框架，使 AI 在解讀命盤時能夠有清晰的邏輯依據。</>,
            card3Title: '我們的內容是如何產生的？',
            card3p: <>本平台的部落格文章由 <strong>AI 系統自動生成</strong>，結合中州派命理理論，分析當下<strong>節氣時令</strong>、<strong>農曆重要時日</strong>，以及近期社會話題，以白話文形式解說命理智慧。我們的目標是讓傳統命理學走入日常生活——不是神秘的算命，而是理解自己、掌握節奏的文化工具。</>,
        },
        faq: {
            heading: '🙋 常見問題',
            items: [
                {
                    q: '紫微斗數和八字有什麼不同？',
                    a: '紫微斗數以星曜和十二宮位為核心，擅長細膩的性格分析與各人生面向（財、官、夫妻、子女等）的立體解析；八字以五行生剋為基礎，著重大運流年的時間節點掌握。兩者各有專長，互為補充。',
                },
                {
                    q: '中州派和其他流派有何差異？',
                    a: '中州派源自中原正統，強調星曜能量等級、四化星互動與飛星邏輯的嚴謹推演，理論體系完整且脈絡清晰。相較於部分現代流派，中州派更忠實地傳承傳統架構，適合系統化學習與 AI 結構化解析。',
                },
                {
                    q: '網站的文章是由誰撰寫？',
                    a: '本網站所有文章均由 AI 系統自動生成。AI 結合中州派命理理論，分析當下節氣、農曆時日與時事話題，以白話文撰寫，提供輕鬆易懂的命理參考內容。',
                },
                {
                    q: 'AI 的分析準確嗎？',
                    a: '本系統採用主流 AI 語言模型，結合傳統中州派理論進行命盤解析。AI 能夠系統性地整合星盤組合，提供客觀參考。命理分析屬於文化傳統，適合作為認識自己、掌握節奏的參考工具，而非絕對預測。',
                },
                {
                    q: '不知道出生時辰怎麼辦？',
                    a: '紫微斗數命盤需要出生時辰才能準確排盤，每兩小時為一個時辰。若不確定，可嘗試最接近的時辰，或根據您的人生重要事件進行「校時」推算，也可諮詢有經驗的命理師協助確認。',
                },
                {
                    q: '部落格文章和算命有什麼不同？',
                    a: <span>部落格文章是以命理角度解析時事、節氣和運勢趨勢，適合一般閱讀與命理知識學習。若需要針對您個人出生資料的命盤分析，請使用<Link href={analysisHref} className="text-purple-600 hover:underline">「開始分析命盤」</Link>功能。</span>,
                },
            ],
        },
        cta: {
            heading: '準備好探索您的命運了嗎？',
            sub: <>結合傳統中州派智慧與現代 AI 技術<br />為您提供最專業、最易懂的命理分析</>,
            button: '🚀 立即開始 AI 命理分析',
            disclaimer: '⚠️ 本服務僅供娛樂和文化學習參考，不應作為重要人生決策的依據',
        },
        footer: {
            copyright: '© 2024 AI 紫微斗數命盤計算系統 | 基於傳統中州派理論',
            privacy: '隱私政策',
            pricing: '價格方案',
            analysis: '開始分析',
        },
    };

    return (
        <>
            <main>
                {/* Hero */}
                <section className="container mx-auto px-4 py-16 text-center">
                    <h1 className="text-5xl md:text-6xl font-bold mb-6 gradient-text">{t.hero.title}</h1>
                    <p className="text-xl md:text-2xl text-gray-700 mb-8 max-w-3xl mx-auto whitespace-pre-line">
                        {t.hero.subtitle}
                    </p>
                    <Link
                        href={analysisHref}
                        className="inline-block bg-gradient-to-r from-purple-600 to-blue-600 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:from-purple-700 hover:to-blue-700 transition-all shadow-lg hover:shadow-xl"
                    >
                        {t.hero.cta}
                    </Link>
                </section>

                {/* About */}
                <section id="about" className="container mx-auto px-4 py-16">
                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-12">
                            <span className="inline-block bg-purple-100 text-purple-700 text-sm font-semibold px-4 py-1.5 rounded-full mb-4">
                                {t.about.badge}
                            </span>
                            <h2 className="text-4xl font-bold text-gray-900 mb-4">{t.about.heading}</h2>
                            <p className="text-gray-500 text-lg max-w-2xl mx-auto">{t.about.sub}</p>
                        </div>
                        <div className="space-y-6">
                            <div className="bg-white rounded-2xl shadow-md p-8 border-l-4 border-purple-500">
                                <div className="flex items-start gap-5">
                                    <div className="flex-shrink-0 w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center text-2xl">📜</div>
                                    <div>
                                        <h3 className="text-xl font-bold text-gray-800 mb-4">{t.about.card1Title}</h3>
                                        <p className="text-gray-600 leading-relaxed mb-3">{t.about.card1p1}</p>
                                        <p className="text-gray-600 leading-relaxed mb-3">{t.about.card1p2}</p>
                                        <p className="text-gray-600 leading-relaxed">{t.about.card1p3}</p>
                                    </div>
                                </div>
                            </div>
                            <div className="bg-white rounded-2xl shadow-md p-8 border-l-4 border-blue-500">
                                <div className="flex items-start gap-5">
                                    <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center text-2xl">🏛️</div>
                                    <div>
                                        <h3 className="text-xl font-bold text-gray-800 mb-4">{t.about.card2Title}</h3>
                                        <p className="text-gray-600 leading-relaxed">{t.about.card2p}</p>
                                    </div>
                                </div>
                            </div>
                            <div className="bg-white rounded-2xl shadow-md p-8 border-l-4 border-indigo-500">
                                <div className="flex items-start gap-5">
                                    <div className="flex-shrink-0 w-12 h-12 bg-indigo-100 rounded-xl flex items-center justify-center text-2xl">🤖</div>
                                    <div>
                                        <h3 className="text-xl font-bold text-gray-800 mb-4">{t.about.card3Title}</h3>
                                        <p className="text-gray-600 leading-relaxed">{t.about.card3p}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* FAQ */}
                <section id="faq" className="container mx-auto px-4 py-16">
                    <div className="max-w-4xl mx-auto">
                        <h2 className="text-4xl font-bold text-center mb-12 text-purple-600">{t.faq.heading}</h2>
                        <div className="space-y-4">
                            {t.faq.items.map((item, i) => (
                                <details key={i} className="bg-white rounded-xl shadow-md p-6 group">
                                    <summary className="font-bold text-lg text-gray-800 cursor-pointer list-none flex justify-between items-center">
                                        {item.q}
                                        <span className="text-purple-500 transition-transform group-open:rotate-180 inline-block ml-4 flex-shrink-0">▼</span>
                                    </summary>
                                    <p className="mt-4 text-gray-700 leading-relaxed">{item.a}</p>
                                </details>
                            ))}
                        </div>
                    </div>
                </section>

                {/* CTA */}
                <section className="container mx-auto px-4 py-16">
                    <div className="max-w-4xl mx-auto">
                        <div className="bg-gradient-to-r from-purple-600 via-blue-600 to-indigo-600 rounded-2xl shadow-2xl p-12 text-center text-white">
                            <h2 className="text-4xl md:text-5xl font-bold mb-6">{t.cta.heading}</h2>
                            <p className="text-xl mb-8 text-white/90">{t.cta.sub}</p>
                            <Link
                                href={analysisHref}
                                className="inline-block bg-white text-purple-600 px-10 py-5 rounded-lg text-xl font-bold hover:bg-gray-100 transition-all shadow-lg hover:shadow-xl"
                            >
                                {t.cta.button}
                            </Link>
                            <p className="mt-6 text-white/80 text-sm">{t.cta.disclaimer}</p>
                        </div>
                    </div>
                </section>
            </main>

            {/* Footer */}
            <footer className="bg-gray-800 text-white py-8 mt-16">
                <div className="container mx-auto px-4">
                    <div className="text-center space-y-4">
                        <p className="text-gray-400">{t.footer.copyright}</p>
                        <div className="flex justify-center space-x-6 text-sm">
                            <Link href={`/${locale}/privacy-policy`} className="text-gray-400 hover:text-white transition-colors">
                                {t.footer.privacy}
                            </Link>
                            <Link href={`/${locale}/pricing`} className="text-gray-400 hover:text-white transition-colors">
                                {t.footer.pricing}
                            </Link>
                            <Link href={analysisHref} className="text-gray-400 hover:text-white transition-colors">
                                {t.footer.analysis}
                            </Link>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    );
}
